import Logo from "./logo.svg";
import LogoTitle from "./logo_title.svg";
import CheckCircle from "./check_circle.svg";
import Mail from "./mail.svg";
import Share from "./share.svg";
import Edit from "./editIcon.svg";
export { Logo, LogoTitle };
export { CheckCircle };
export { Mail };
export { Share, Edit };
