name: Build, Release, and Deploy to EC2

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 코드 체크아웃
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Node.js 설치 및 빌드
    - name: Install dependencies and build
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Build Next.js
      run: |
        npm ci
        npm run build
        zip -r build.zip .next

    # 3. GitHub Release 생성 및 빌드 파일 업로드
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: build.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
