name: Release and Deploy

on:
  push:
    tags:
      - 'v*' # v로 시작하는 모든 태그에서 트리거

permissions:
  contents: write  # 릴리즈 생성 권한
  id-token: write   # id-token 사용 권한 (필요 시)

env:
  EC2_USER: ubuntu
  EC2_PATH: /home/ubuntu
  PEM_FILE: private_key.pem

jobs:
  release-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. 코드 체크아웃
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Node.js 설치 및 빌드
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies and Build
      run: |
        npm ci
        npm run build
        zip -r build.zip .next

    # 3. GitHub Release 생성
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: build.zip
        name: "Release ${{ github.ref_name }}"
        tag_name: ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # 4. EC2 배포 준비
    - name: Create PEM file
      run: echo "${{ secrets.EC2_PRIVATE_KEY }}" > $PEM_FILE

    - name: Set PEM file permissions
      run: chmod 600 $PEM_FILE

    - name: Deploy build.zip to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i $PEM_FILE $EC2_USER@${{ secrets.EC2_HOST }} << EOF
          set -e  # 에러 시 종료
          cd $EC2_PATH
          
          # 기존 build.zip 삭제
          if [ -f build.zip ]; then
            rm build.zip
          fi

          # Release에서 최신 build.zip 다운로드
          gh release download ${{ github.ref_name }} --repo oyc0401/rokafmail --pattern "build.zip"
        EOF

    # 5. EC2에서 프로젝트 실행
    - name: Run Project on EC2
      run: |
        ssh -t -o StrictHostKeyChecking=no -i $PEM_FILE $EC2_USER@${{ secrets.EC2_HOST }} << 'EOF'
          bash --login $EC2_PATH/deploy.sh
        EOF

    # 6. Clean up
    - name: Clean Up Private Key
      run: rm $PEM_FILE
